version: 0.0.0+{build}

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: minimal

test: off

services:
  - iis

environment:
  WHISKEY_DISABLE_ERROR_FORMAT: True
  matrix:
  - job_name: .NET 4.6.2
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2013

  - job_name: Windows 2012R2
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2015

  - job_name: Windows 2016
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2017

  - job_name: Windows 2019
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2022

  - job_name: PowerShell 7
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2022


artifacts:
- path: .output\*


for:
# Build in Windows PowerShell
- matrix:
    only:
    - job_group: ps
  build_script:
  - ps: |
        iwr https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1 | iex | Format-Table
        .\build.ps1

# Build in PowerShell
- matrix:
    only:
    - job_group: pwsh
  build_script:
  - pwsh: |
        iwr https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1 | iex | Format-Table
        .\build.ps1
