version: 0.0.0+{build}

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: minimal

test: off

services:
  - iis

environment:
  WHISKEY_DISABLE_ERROR_FORMAT: True
  matrix:
  - job_name: Windows Server 2016, Windows PowerShell 5.1
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2017


artifacts:
- path: .output\*


for:
# Build in Windows PowerShell
- matrix:
    only:
    - job_group: ps
  build_script:
  - ps: .\build.ps1

# Build in PowerShell
- matrix:
    only:
    - job_group: pwsh
  build_script:
  - pwsh: ./build.ps1
